(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(*loading this file will automatically load all the cad extension files*)

cadhelperdirectory = "C:\\Documents and Settings\\neil\\My Documents\\projects - interests - hobbies\\mathematica extensions\\Mathematica CAD stuff\\"; (*this is the directory containing the several mathematica files which contain the functions I use for CAD projects*);


(*this loads all the .m files in the cadhelperdirectory*)
Block[
{filenames},
SetDirectory[cadhelperdirectory];
filenames = FileNames[];

For[
i=1, i<= Length[filenames ], i++,
If[
StringMatchQ[filenames[[i]],___ ~~ ".m"],
Get[cadhelperdirectory <> filenames[[i]]];
];
];
]

